name: Build ItzWaypoint Mod

on: [push, pull_request]

jobs Rerun
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # THIS IS THE NEW COMMAND TO FORCE A CLEAN BUILD
      - name: Build with Gradle (Forced Clean)
        run: ./gradlew build --no-build-cache --refresh-dependencies

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ItzWaypoint-1.21.1
          path: build/libs/*.jar
