name: Build ItzWaypoint Mod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Setup Gradle and Clear Cache
        uses: gradle/actions/setup-gradle@v3
        with:
          # This is a new setting to help with caching
          cache-read-only: false

      # THIS IS THE NEW, CRITICAL STEP
      # This command forces the build to be clean
      - name: Build with Gradle (Clean Build)
        run: ./gradlew build --no-daemon --no-build-cache --refresh-dependencies

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ItzWaypoint-1.21.1
          path: build/libs/*.jar
